### ISSUE TITLE
Run GATK tools

### ISSUE THREAD

**Issue by abearab** [goodarzilab/WES#1]
# Current Pipeline
Here we are aiming to implement different tools and datasets that enable us to efficiently analyze WES data. In this issue we are listing our progress as tasks and links to related materials. 
## Tasks 
- [x] `bash` code to prepare `bam` file
- [x] Setup GATK pipeline and select sub-tools in order 
  - [ ] Divide SNP and InDel analysis
  - [ ] Set up CNV analysis 
  - [ ] Allele frequency comparison between conditions and heatmap visualization
    > It's probably through [this](https://vcftools.github.io/documentation.html#freq) 
- [x] `multiqc` on GATK subtools. 

## Related tools 
- [Welcome to WARP | WARP](https://broadinstitute.github.io/warp/)
- [GATK Tools Documentation](https://gatk.broadinstitute.org/hc/en-us/articles/4409907944219--Tool-Documentation-Index)
  - [Variant Calling Pipeline using GATK4](https://gencore.bio.nyu.edu/variant-calling-pipeline-gatk4/)
  - [tumor-only-variant-calling-workflow](https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline/#tumor-only-variant-calling-workflow)
  - [Germline short variant discovery (SNPs + Indels) – GATK](https://gatk.broadinstitute.org/hc/en-us/articles/360035535932-Germline-short-variant-discovery-SNPs-Indels)
  - [GDC DNA-Seq analysis pipeline](https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline/#dna-seq-analysis-pipeline)
- [`google/deepvariant`](https://github.com/google/deepvariant)
- [strelka (Illumina)](https://github.com/Illumina/strelka)
- [SnpEff](https://pcingola.github.io/SnpEff/)
- [`VCFtools`](https://vcftools.github.io/documentation.html)
- [COSMIC, the Catalogue Of Somatic Mutations In Cancer](https://cancer.sanger.ac.uk/cosmic)
- [Celligner](https://depmap.org/portal/celligner/): Tumor + cell line model alignment
### Mutation analysis 
- [`PertInInt`](https://github.com/Singh-Lab/PertInInt)
